module.exports = {
  JWT_EXP_LOGIN: "3h",
  JWT_EXP_REFRESH: "1d",
  JWT_EXP_RESET_PSW: "5m",
  JWT_SECRET_LOGIN: process.env.JWT_SECRET_LOGIN,
  JWT_SECRET_REFRESH_LOGIN: process.env.JWT_SECRET_REFRESH_LOGIN,
  JWT_SECRET_RESET_PSW: process.env.JWT_SECRET_RESET_PSW
};
